import Head from 'next/head'
import Image from 'next/image'
import {FlexBox} from './../styles/FlexBox'
import styled from 'styled-components'

const Title = styled.h1`
  // font-size: 50px;
  color: ${({ theme }) => theme.colors.primary};
  `

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FlexBox justifyContent="center">
        <Title>Home page</Title>
      </FlexBox>
      {/* <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div> */}

    </>
  )
}
